//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsGSUDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketsTable()
        {
            this.PaymentHistoryTables = new HashSet<PaymentHistoryTable>();
        }
    
        public int TicketID { get; set; }
        public int TicketQuantity { get; set; }
        public int TicketPrice { get; set; }
        public int EventID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModfiedDate { get; set; }
        public int TicketsPurchased { get; set; }
        public int TicketsRemining { get; set; }
        public int isDelete { get; set; }
    
        public virtual EventsTable EventsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistoryTable> PaymentHistoryTables { get; set; }
    }
}
